name: build libnserial for linux
 
on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        
    runs-on: ${{ matrix.os }}
    env:
      APP_VERSION: 1.0.${{ github.run_number }}

    steps:        
    - uses: actions/checkout@v3
 
    - name: Build libnserial
      working-directory: dll/serialunix
      run: ./build.sh

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: lib-${{ matrix.os }}
        path: dll/serialunix/bin      
      if: ${{ always() }}
