name: build libnserial for linux

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      APP_VERSION: 1.0.${{ github.run_number }}

    steps:        
    - uses: actions/checkout@v3
 
    - name: Build
      working-directory: dll/serialunix
      run: ./build.sh

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: library
        path: build      
      if: ${{ always() }}
